export const APP_STATE_KEY = "app";
export const CATEGORY_STATE_KEY = "category";
export const TRENDING_BLOGS_STATE_KEY = "trending";
export const NAMESPACE = "APP/";

// GLOBAL
export const SET_DATA = `${NAMESPACE}SET_DATA`;

// CATEGORY
export const FETCH_CATEGORY = `${NAMESPACE}FETCH_CATEGORY`;
export const FETCHING_CATEGORY = `${NAMESPACE}FETCHING_CATEGORY`;
export const FETCH_CATEGORY_SUCCESS = `${NAMESPACE}FETCH_CATEGORY_SUCCESS`;
export const FETCH_CATEGORY_ERROR = `${NAMESPACE}FETCH_CATEGORY_ERROR`;

// TRENDING CATEGORY
export const FETCH_TRENDING_BLOGS = `${NAMESPACE}FETCH_TRENDING_BLOGS`;
export const FETCHING_TRENDING_BLOGS = `${NAMESPACE}FETCHING_TRENDING_BLOGS`;
export const FETCH_TRENDING_BLOGS_SUCCESS = `${NAMESPACE}FETCH_TRENDING_BLOGS_SUCCESS`;
export const FETCH_TRENDING_BLOGS_ERROR = `${NAMESPACE}FETCH_TRENDING_BLOGS_ERROR`;
