export const APP_STATE_KEY = "app";
export const CATEGORY_STATE_KEY = "category";
export const NAMESPACE = "APP/";

// GLOBAL
export const SET_DATA = `${NAMESPACE}SET_DATA`;

// CATEGORY
export const FETCH_CATEGORY = `${NAMESPACE}FETCH_CATEGORY`;
export const FETCHING_CATEGORY = `${NAMESPACE}FETCHING_CATEGORY`;
export const FETCH_CATEGORY_SUCCESS = `${NAMESPACE}FETCH_CATEGORY_SUCCESS`;
export const FETCH_CATEGORY_ERROR = `${NAMESPACE}FETCH_CATEGORY_ERROR`;
