export const TODAYS_SPOTLIGHT_STATE_KEY = "todaysSpotlight";
export const NAMESPACE = "TODAY_SPOTLIGHT/";

// TODAYs SPOTLIGHT
export const FETCH_TODAY_SPOTLIGHT = `${NAMESPACE}FETCH_TODAY_SPOTLIGHT`;
export const FETCHING_TODAY_SPOTLIGHT = `${NAMESPACE}FETCHING_TODAY_SPOTLIGHT`;
export const FETCH_TODAY_SPOTLIGHT_SUCCESS = `${NAMESPACE}FETCH_TODAY_SPOTLIGHT_SUCCESS`;
export const FETCH_TODAY_SPOTLIGHT_ERROR = `${NAMESPACE}FETCH_TODAY_SPOTLIGHT_ERROR`;
