export const BLOG_DETAIL_STATE_KEY = "blogDetail";
export const NAMESPACE = "BLOG_DETAIL/";

// TODAYs SPOTLIGHT
export const FETCH_BLOG_DETAIL = `${NAMESPACE}FETCH_BLOG_DETAIL`;
export const FETCHING_BLOG_DETAIL = `${NAMESPACE}FETCHING_BLOG_DETAIL`;
export const FETCH_BLOG_DETAIL_SUCCESS = `${NAMESPACE}FETCH_BLOG_DETAIL_SUCCESS`;
export const FETCH_BLOG_DETAIL_ERROR = `${NAMESPACE}FETCH_BLOG_DETAIL_ERROR`;
export const RESET_BLOG_DETAIL = `${NAMESPACE}RESET_BLOG_DETAIL`;
